The-Futuristics-18158/intothedeep

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/LinearSlide.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/OdometryPod.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/SlideTargetHeight.java
=> Merge into master

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Camera.java
=> Add new camera functions to master

TeamCode/build.gradle, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/ManualDrive.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/DriveTrain.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Odometry.java, build.common.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Closed-Loop-Drive

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CommandGroups/ExampleCommandGroup.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/FollowPath.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/ManualDrive.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Camera.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/DriveTrain.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Gyro.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/LinearSlide.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/OctQuad.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Odometry.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/OdometryPod.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/VirtualDriveTrain.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/VirtualOdometry.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/Utils.java
Add path-following function to master.
=> Functionsfor pathing

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Claw.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ClawLastYear.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ClawState.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ElbowJoint.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ElbowPosition.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/FlappyFlappyWrist.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/LinearSlide.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/PivotingWrist.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ShoulderJoint.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ShoulderPosition.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
This long running branch has to be brought back into master so we can continue the next phase of development.
=> Pivoting wrist

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/ClawCamera.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/MainTeleop.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/VisionProcessorMode.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/VisionSystem.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/ColorAndOrientationDetect.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/ColorDetect.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/DetectedColor.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/DetectedColorWithAngle.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/HSVSaturationProcessor.java
This vision can identify colours and angles
=> Vision test

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Blinkin.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/BlinkinColour.java
=> preparing to pull into master

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/FollowPath.java
If end speed defined as zero, followpath sets drive speeds to 0 upon end of path.
=> FollowPath ending condition

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Blinkin.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/OctQuad.java
=> added some comments

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/FollowPath.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/GoToNextDropOff.java
Add drop off position command for testing purposes.
=> Follow path update for malformed paths

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/AutoFunctions.java
=> Red vs Blue Coordinate Translation utility

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java
=> Left-side auto now has leftvsright translation

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Blinkin.java
=> Made blinkin colours persist

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/MoveToPose.java
=> Add new MoveToPose command.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/SelectCommandOnMode.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Blinkin.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/OperatingMode.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Vision/Camera.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/BlinkinColour.java
=> Add operating mode

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/OperatingMode.java
=> Use L-trigger for mode.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/Claw/ToggleClaw.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java
=> Reassign toggle claw to right-bumper

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/Drive/FollowPath.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/DriveTrain.java
Update followpath ending function to use new stopdrive.
=> Add StopDrive() command to DriveTrain subsystem.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CommandGroups/Auto/LeftSideAuto87Pts.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CommandGroups/AutomatedMovements/GroundCyclingAuto.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CommandGroups/AutomatedMovements/HighBucketDeposit.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/Drive/FollowPath.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/DriveTrain.java
Moved feedback speed control from drive function to periodic. PIF gains kept but robot speed tracking performance should be checked again.
=> Drive motor control rev 1.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/Drive/MoveToPose.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/SelectCommandOnMode.java
They no longer use scheduler for subcommand, but now call individual functions of the subcommand.
=> Update to command wrappers.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CommandGroups/AutomatedMovements/WallPickUp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/Drive/MoveToPickup.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/Drive/MoveToWallPickup.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotContainer.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Vision/Camera.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utility/VisionProcessorMode.java
=> Guided wall pickup functionality..

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm/Shoulder/ShoulderJoint.java
=> Shoulder profiling

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm/Shoulder/ShoulderJoint.java
=> Update. Motor motor now includes motion profile as before.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm/Elbow/ElbowJoint.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm/Wrist/FlappyFlappyWrist.java
=> Update for test.
